import { DashboardData } from '../../types';

export const mockDashboardData: DashboardData = {
  objectives: [
    {
      id: 'obj-1',
      audience: 'Cliente',
      title: 'Receber promoções e campanhas no celular',
      description: 'A oficina divulga ofertas segmentadas de pneus, peças e serviços com chamadas para orçamento ou agendamento.',
    },
    {
      id: 'obj-2',
      audience: 'Cliente',
      title: 'Acompanhar o status do carro em tempo real',
      description: 'Cada atendimento mostra a etapa atual do serviço e o cliente é avisado quando o veículo está pronto para retirada.',
    },
    {
      id: 'obj-3',
      audience: 'Cliente',
      title: 'Consultar histórico e pedir orçamento',
      description: 'O app centraliza histórico de manutenção, catálogo e solicitação de orçamento para pneus, peças e serviços.',
    },
    {
      id: 'obj-4',
      audience: 'Empresa',
      title: 'Gerenciar atendimentos, orçamentos, status e notificações',
      description: 'A área administrativa coordena filas de atendimento, respostas comerciais, lembretes trimestrais e mensagens transacionais.',
    },
  ],
  customer: {
    name: 'Lucas Martins',
    unit: 'Impacto Prime • Taboão da Serra',
    nextRevision: '20 jun 2026',
    memberSince: 'Cliente desde jan 2024',
  },
  appModules: [
    {
      id: 'mod-1',
      name: 'Autenticação',
      description: 'Centraliza login, cadastro, sessão, recuperação de acesso e vínculo do cliente com seus veículos.',
      responsibilities: ['Login e cadastro', 'Sessão do usuário', 'Recuperação de acesso'],
    },
    {
      id: 'mod-2',
      name: 'Clientes',
      description: 'Mantém o perfil do cliente, preferências de contato e visão consolidada do relacionamento com a oficina.',
      responsibilities: ['Perfil cadastral', 'Preferências', 'Relacionamento'],
    },
    {
      id: 'mod-3',
      name: 'Veículos',
      description: 'Organiza múltiplos veículos por cliente, dados técnicos, quilometragem e contexto operacional.',
      responsibilities: ['Cadastro de veículos', 'Dados técnicos', 'Quilometragem e observações'],
    },
    {
      id: 'mod-4',
      name: 'Serviços',
      description: 'Gerencia ordens de serviço, timeline operacional e responsáveis técnicos durante o atendimento.',
      responsibilities: ['Ordens de serviço', 'Timeline do atendimento', 'Equipe responsável'],
    },
    {
      id: 'mod-5',
      name: 'Orçamento',
      description: 'Recebe solicitações, controla protocolos e conecta cliente e equipe administrativa até a aprovação.',
      responsibilities: ['Solicitação digital', 'Protocolos', 'Aprovação e retorno'],
    },
    {
      id: 'mod-6',
      name: 'Catálogo',
      description: 'Expõe produtos, serviços e promoções disponíveis para consulta e conversão em orçamento.',
      responsibilities: ['Produtos e serviços', 'Preço e estoque', 'Promoções'],
    },
    {
      id: 'mod-7',
      name: 'Notificações',
      description: 'Orquestra alertas de promoção, mudança de status, retirada do veículo e lembretes periódicos.',
      responsibilities: ['Push notifications', 'Alertas operacionais', 'Campanhas'],
    },
    {
      id: 'mod-8',
      name: 'Histórico',
      description: 'Preserva o histórico de manutenção por veículo para consulta futura e retenção do cliente.',
      responsibilities: ['Manutenções executadas', 'Custos e datas', 'Base para recorrência'],
    },
  ],
  domainEntities: [
    {
      id: 'ent-1',
      name: 'Cliente',
      description: 'Representa o usuário proprietário do relacionamento com a oficina.',
      keyFields: ['id', 'nome', 'email', 'telefone'],
    },
    {
      id: 'ent-2',
      name: 'Veículo',
      description: 'Agrupa dados do automóvel vinculado ao cliente e ao ciclo de manutenção.',
      keyFields: ['id', 'clienteId', 'placa', 'modelo'],
    },
    {
      id: 'ent-3',
      name: 'Serviço',
      description: 'Registra a ordem em atendimento, escopo técnico e custos previstos ou realizados.',
      keyFields: ['id', 'veiculoId', 'status', 'valorEstimado'],
    },
    {
      id: 'ent-4',
      name: 'StatusServiço',
      description: 'Define as etapas do fluxo operacional exibidas ao cliente e atualizadas pela oficina.',
      keyFields: ['id', 'servicoId', 'etapa', 'dataAtualizacao'],
    },
    {
      id: 'ent-5',
      name: 'Orçamento',
      description: 'Controla a solicitação comercial do cliente até resposta e aprovação.',
      keyFields: ['id', 'clienteId', 'veiculoId', 'status'],
    },
    {
      id: 'ent-6',
      name: 'Produto',
      description: 'Representa itens ou serviços exibidos no catálogo para venda ou cotação.',
      keyFields: ['id', 'nome', 'categoria', 'preco'],
    },
    {
      id: 'ent-7',
      name: 'Promoção',
      description: 'Materializa campanhas com vigência e destaque comercial no app.',
      keyFields: ['id', 'titulo', 'dataInicio', 'dataFim'],
    },
    {
      id: 'ent-8',
      name: 'Notificação',
      description: 'Armazena comunicações enviadas ao cliente por evento operacional ou marketing.',
      keyFields: ['id', 'clienteId', 'tipo', 'dataEnvio'],
    },
    {
      id: 'ent-9',
      name: 'HistóricoManutenção',
      description: 'Consolida intervenções já executadas para consulta técnica e relacionamento.',
      keyFields: ['id', 'veiculoId', 'servicoId', 'dataExecucao'],
    },
  ],
  kpis: [
    { id: 'kpi-1', label: 'Veículos cadastrados', value: '2' },
    { id: 'kpi-2', label: 'Serviço em andamento', value: '1 ativo' },
    { id: 'kpi-3', label: 'Solicitações de orçamento', value: '3 este mês' },
  ],
  shortcuts: [
    {
      id: 'short-1',
      label: 'Acompanhar serviço',
      description: 'Timeline em tempo real do carro na oficina.',
    },
    {
      id: 'short-2',
      label: 'Solicitar orçamento',
      description: 'Envio rápido de pneus, peças e revisões.',
    },
    {
      id: 'short-3',
      label: 'Loja de pneus',
      description: 'Catálogo com itens em destaque da unidade.',
    },
    {
      id: 'short-4',
      label: 'Histórico do veículo',
      description: 'Tudo o que já foi feito no carro.',
    },
  ],
  featureHighlights: [
    {
      id: 'feature-1',
      title: 'RF04 • Status do serviço',
      description: 'Cliente acompanha cada etapa: recebimento, análise, aprovação, execução e retirada.',
    },
    {
      id: 'feature-2',
      title: 'RF07/RF08 • Orçamento digital',
      description: 'Solicitação vai para o admin e retorna para o cliente com protocolo.',
    },
    {
      id: 'feature-3',
      title: 'RF10 • Lembrete trimestral',
      description: 'Notificações automatizadas ajudam na retenção e recorrência de revisão.',
    },
  ],
  vehicles: [
    {
      id: 'veh-1',
      plate: 'BRA2E19',
      brand: 'Jeep',
      model: 'Compass Longitude',
      year: 2021,
      mileage: 48210,
      notes: 'Cliente prefere contato via WhatsApp após 18h.',
      statusLabel: 'Em atendimento',
    },
    {
      id: 'veh-2',
      plate: 'GOL9A45',
      brand: 'Volkswagen',
      model: 'Gol 1.6 MSI',
      year: 2019,
      mileage: 76340,
      notes: 'Uso diário para trabalho, priorizar revisão rápida.',
      statusLabel: 'Revisão trimestral pendente',
    },
  ],
  activeServices: [
    {
      id: 'srv-1',
      vehicleId: 'veh-1',
      title: 'Revisão completa + alinhamento',
      description: 'Troca de óleo, filtros, alinhamento, scanner e inspeção do sistema de freios.',
      eta: 'Hoje, 17:40',
      budget: 'R$ 1.280,00',
      technician: 'Técnico responsável: Marcos',
      steps: [
        { label: 'Veículo recebido', completed: true },
        { label: 'Em análise', completed: true },
        { label: 'Orçamento em preparação', completed: true },
        { label: 'Serviço aprovado', completed: true },
        { label: 'Em execução', completed: true, current: true },
        { label: 'Finalizado', completed: false },
        { label: 'Pronto para retirada', completed: false },
      ],
    },
  ],
  promotions: [
    {
      id: 'pro-1',
      title: 'Revisão completa com desconto',
      description: 'Troca de óleo premium + filtro + checklist com 20 itens em promoção nesta semana.',
      highlight: '15% OFF',
      cta: 'Agendar agora',
    },
    {
      id: 'pro-2',
      title: 'Pneus aro 18 com instalação grátis',
      description: 'Marcas premium com alinhamento e balanceamento inclusos.',
      highlight: '4x sem juros',
      cta: 'Solicitar orçamento',
    },
    {
      id: 'pro-3',
      title: 'Campanha freios + suspensão',
      description: 'Avaliação gratuita para pastilhas, discos, amortecedores e pivôs.',
      highlight: 'Check-up grátis',
      cta: 'Receber detalhes',
    },
  ],
  catalog: [
    {
      id: 'cat-1',
      name: 'Pneu Michelin Primacy 4',
      category: 'Pneus',
      description: 'Alta aderência e conforto para uso urbano e rodoviário.',
      price: 'R$ 899,00',
      stock: '8 unidades',
    },
    {
      id: 'cat-2',
      name: 'Bateria Moura 60Ah',
      category: 'Baterias',
      description: 'Excelente partida e durabilidade para veículos leves.',
      price: 'R$ 579,00',
      stock: '12 unidades',
    },
    {
      id: 'cat-3',
      name: 'Kit pastilha dianteira Bosch',
      category: 'Freios',
      description: 'Reposição com baixo ruído e maior vida útil.',
      price: 'R$ 249,00',
      stock: '15 kits',
    },
    {
      id: 'cat-4',
      name: 'Revisão preventiva 40 mil km',
      category: 'Serviços',
      description: 'Inspeção geral com scanner, fluidos e filtros essenciais.',
      price: 'Sob consulta',
      stock: 'Agenda disponível',
    },
  ],
  history: [
    {
      id: 'his-1',
      vehicleId: 'veh-1',
      title: 'Troca de óleo',
      date: '10 jan 2026',
      details: 'Óleo sintético 5W30, filtro de óleo e revisão visual de vazamentos.',
      amount: 'R$ 390,00',
    },
    {
      id: 'his-2',
      vehicleId: 'veh-1',
      title: 'Alinhamento e balanceamento',
      date: '10 jan 2026',
      details: 'Ajuste da geometria e balanceamento das quatro rodas.',
      amount: 'R$ 180,00',
    },
    {
      id: 'his-3',
      vehicleId: 'veh-1',
      title: 'Troca de pastilhas de freio',
      date: '22 mar 2026',
      details: 'Substituição do jogo dianteiro com limpeza do conjunto.',
      amount: 'R$ 420,00',
    },
    {
      id: 'his-4',
      vehicleId: 'veh-2',
      title: 'Revisão preventiva',
      date: '15 jun 2026',
      details: 'Checklist de segurança, bateria, freios, suspensão e fluidos.',
      amount: 'R$ 610,00',
    },
  ],
  notifications: [
    {
      id: 'not-1',
      type: 'service',
      title: 'Serviço em andamento',
      message: 'Seu Compass já está em execução na oficina e segue dentro do prazo estimado.',
      date: 'Hoje • 14:32',
      read: false,
    },
    {
      id: 'not-2',
      type: 'pickup',
      title: 'Veículo pronto para retirada',
      message: 'Seu veículo já está pronto para retirada na Impacto Prime: Taboão da Serra.',
      date: 'Hoje • 17:45',
      read: false,
    },
    {
      id: 'not-3',
      type: 'promo',
      title: 'Promoção da semana',
      message: 'Revisão completa com 15% de desconto nesta semana. Aproveite!',
      date: '19 mar 2026',
      read: true,
    },
    {
      id: 'not-4',
      type: 'revision',
      title: 'Lembrete de revisão periódica',
      message: 'Já faz 3 meses desde sua última revisão. Agende uma nova visita na Impacto Prime.',
      date: '18 mar 2026',
      read: true,
    },
  ],
  reminderCadences: [
    {
      id: 'rem-1',
      title: 'Revisão preventiva automática',
      cadence: 'A cada 3 meses',
      trigger: 'Disparo após a data da última manutenção concluída.',
      description: 'Envia push, banner no app e CTA para reagendar revisão ou solicitar nova avaliação.',
    },
    {
      id: 'rem-2',
      title: 'Recuperação de orçamento sem resposta',
      cadence: '48 horas depois',
      trigger: 'Ativado quando o cliente visualiza a cotação e ainda não aprova.',
      description: 'A equipe comercial recebe alerta e o cliente recebe lembrete amigável com a oferta vigente.',
    },
  ],
  adminWorkspace: [
    {
      id: 'wrk-1',
      owner: 'Atendimento',
      title: 'Gestão de entrada e andamento do serviço',
      description: 'Registrar check-in do veículo, atualizar etapas da OS e sinalizar o momento de retirada.',
    },
    {
      id: 'wrk-2',
      owner: 'Comercial',
      title: 'Orçamentos de pneus, peças e serviços',
      description: 'Receber pedidos vindos do app, montar propostas e acompanhar conversão de campanhas.',
    },
    {
      id: 'wrk-3',
      owner: 'Relacionamento',
      title: 'Notificações e campanhas',
      description: 'Programar promoções, avisos transacionais e lembretes periódicos com segmentação por cliente ou veículo.',
    },
  ],
  adminTasks: [
    {
      id: 'adm-1',
      title: 'Responder orçamento de pneus',
      description: 'Cliente Lucas Martins solicitou cotação para 4 pneus aro 18.',
      status: 'Pendente',
    },
    {
      id: 'adm-2',
      title: 'Atualizar status do Compass',
      description: 'Mover serviço para etapa Finalizado e liberar retirada.',
      status: 'Em andamento',
    },
    {
      id: 'adm-3',
      title: 'Cadastrar campanha sazonal',
      description: 'Subir promoção de alinhamento e balanceamento de abril.',
      status: 'Planejado',
    },
  ],
};
