import { DashboardData } from '../../types';

export const mockDashboardData: DashboardData = {
  objectives: [
    {
      id: 'obj-1',
      audience: 'Cliente',
      title: 'Receber promoções e campanhas no celular',
      description: 'A oficina divulga ofertas segmentadas de pneus, peças e serviços com chamadas para orçamento ou agendamento.',
    },
    {
      id: 'obj-2',
      audience: 'Cliente',
      title: 'Acompanhar o status do carro em tempo real',
      description: 'Cada atendimento mostra a etapa atual do serviço e o cliente é avisado quando o veículo está pronto para retirada.',
    },
    {
      id: 'obj-3',
      audience: 'Cliente',
      title: 'Consultar histórico e pedir orçamento',
      description: 'O app centraliza histórico de manutenção, catálogo e solicitação de orçamento para pneus, peças e serviços.',
    },
    {
      id: 'obj-4',
      audience: 'Empresa',
      title: 'Gerenciar atendimentos, orçamentos, status e notificações',
      description: 'A área administrativa coordena filas de atendimento, respostas comerciais, lembretes trimestrais e mensagens transacionais.',
    },
  ],
  customer: {
    name: 'Lucas Martins',
    unit: 'Impacto Prime • Taboão da Serra',
    nextRevision: '20 jun 2026',
    memberSince: 'Cliente desde jan 2024',
  },
  appModules: [
    {
      id: 'mod-1',
      name: 'Autenticação',
      description: 'Centraliza login, cadastro, sessão, recuperação de acesso e vínculo do cliente com seus veículos.',
      responsibilities: ['Login e cadastro', 'Sessão do usuário', 'Recuperação de acesso'],
    },
    {
      id: 'mod-2',
      name: 'Clientes',
      description: 'Mantém o perfil do cliente, preferências de contato e visão consolidada do relacionamento com a oficina.',
      responsibilities: ['Perfil cadastral', 'Preferências', 'Relacionamento'],
    },
    {
      id: 'mod-3',
      name: 'Veículos',
      description: 'Organiza múltiplos veículos por cliente, dados técnicos, quilometragem e contexto operacional.',
      responsibilities: ['Cadastro de veículos', 'Dados técnicos', 'Quilometragem e observações'],
    },
    {
      id: 'mod-4',
      name: 'Serviços',
      description: 'Gerencia ordens de serviço, timeline operacional e responsáveis técnicos durante o atendimento.',
      responsibilities: ['Ordens de serviço', 'Timeline do atendimento', 'Equipe responsável'],
    },
    {
      id: 'mod-5',
      name: 'Orçamento',
      description: 'Recebe solicitações, controla protocolos e conecta cliente e equipe administrativa até a aprovação.',
      responsibilities: ['Solicitação digital', 'Protocolos', 'Aprovação e retorno'],
    },
    {
      id: 'mod-6',
      name: 'Catálogo',
      description: 'Expõe produtos, serviços e promoções disponíveis para consulta e conversão em orçamento.',
      responsibilities: ['Produtos e serviços', 'Preço e estoque', 'Promoções'],
    },
    {
      id: 'mod-7',
      name: 'Notificações',
      description: 'Orquestra alertas de promoção, mudança de status, retirada do veículo e lembretes periódicos.',
      responsibilities: ['Push notifications', 'Alertas operacionais', 'Campanhas'],
    },
    {
      id: 'mod-8',
      name: 'Histórico',
      description: 'Preserva o histórico de manutenção por veículo para consulta futura e retenção do cliente.',
      responsibilities: ['Manutenções executadas', 'Custos e datas', 'Base para recorrência'],
    },
  ],
  domainEntities: [
    {
      id: 'ent-1',
      name: 'Cliente',
      description: 'Representa o usuário proprietário do relacionamento com a oficina.',
      keyFields: ['id', 'nome', 'email', 'telefone'],
    },
    {
      id: 'ent-2',
      name: 'Veículo',
      description: 'Agrupa dados do automóvel vinculado ao cliente e ao ciclo de manutenção.',
      keyFields: ['id', 'clienteId', 'placa', 'modelo'],
    },
    {
      id: 'ent-3',
      name: 'Serviço',
      description: 'Registra a ordem em atendimento, escopo técnico e custos previstos ou realizados.',
      keyFields: ['id', 'veiculoId', 'status', 'valorEstimado'],
    },
    {
      id: 'ent-4',
      name: 'StatusServiço',
      description: 'Define as etapas do fluxo operacional exibidas ao cliente e atualizadas pela oficina.',
      keyFields: ['id', 'servicoId', 'etapa', 'dataAtualizacao'],
    },
    {
      id: 'ent-5',
      name: 'Orçamento',
      description: 'Controla a solicitação comercial do cliente até resposta e aprovação.',
      keyFields: ['id', 'clienteId', 'veiculoId', 'status'],
    },
    {
      id: 'ent-6',
      name: 'Produto',
      description: 'Representa itens ou serviços exibidos no catálogo para venda ou cotação.',
      keyFields: ['id', 'nome', 'categoria', 'preco'],
    },
    {
      id: 'ent-7',
      name: 'Promoção',
      description: 'Materializa campanhas com vigência e destaque comercial no app.',
      keyFields: ['id', 'titulo', 'dataInicio', 'dataFim'],
    },
    {
      id: 'ent-8',
      name: 'Notificação',
      description: 'Armazena comunicações enviadas ao cliente por evento operacional ou marketing.',
      keyFields: ['id', 'clienteId', 'tipo', 'dataEnvio'],
    },
    {
      id: 'ent-9',
      name: 'HistóricoManutenção',
      description: 'Consolida intervenções já executadas para consulta técnica e relacionamento.',
      keyFields: ['id', 'veiculoId', 'servicoId', 'dataExecucao'],
    },
  ],
  kpis: [
    { id: 'kpi-1', label: 'Veículos cadastrados', value: '2' },
    { id: 'kpi-2', label: 'Serviço em andamento', value: '1 ativo' },
    { id: 'kpi-3', label: 'Solicitações de orçamento', value: '3 este mês' },
  ],
  shortcuts: [
    {
      id: 'short-1',
      label: 'Acompanhar serviço',
      description: 'Timeline em tempo real do carro na oficina.',
    },
    {
      id: 'short-2',
      label: 'Solicitar orçamento',
      description: 'Envio rápido de pneus, peças e revisões.',
    },
    {
      id: 'short-3',
      label: 'Loja de pneus',
      description: 'Catálogo com itens em destaque da unidade.',
    },
    {
      id: 'short-4',
      label: 'Histórico do veículo',
      description: 'Tudo o que já foi feito no carro.',
    },
  ],
  requirements: [
    {
      id: 'RF01',
      title: 'Cadastro e login de clientes',
      description: 'Permite autenticação, recuperação de acesso e início do relacionamento digital com a oficina.',
      appArea: 'Jornada do cliente',
      status: 'Disponível no MVP',
    },
    {
      id: 'RF02',
      title: 'Cadastro de veículos vinculados ao cliente',
      description: 'Cada cliente pode manter um ou mais veículos com dados principais e contexto de atendimento.',
      appArea: 'Meus veículos',
      status: 'Disponível na demo',
    },
    {
      id: 'RF03',
      title: 'Exibição de promoções da oficina',
      description: 'Mostra campanhas comerciais e chamadas para ação diretamente no app.',
      appArea: 'Promoções e campanhas',
      status: 'Disponível na demo',
    },
    {
      id: 'RF04',
      title: 'Acompanhar status do serviço',
      description: 'Timeline com etapas como análise, aprovação, execução e retirada.',
      appArea: 'Serviço ativo',
      status: 'Disponível na demo',
    },
    {
      id: 'RF05',
      title: 'Notificação de veículo pronto para retirada',
      description: 'Central de notificações destaca quando o carro está liberado pela oficina.',
      appArea: 'Central de notificações',
      status: 'Disponível na demo',
    },
    {
      id: 'RF06',
      title: 'Catálogo de pneus e peças',
      description: 'Lista produtos e serviços com categoria, preço e disponibilidade.',
      appArea: 'Loja / catálogo',
      status: 'Disponível na demo',
    },
    {
      id: 'RF07',
      title: 'Solicitar orçamento de produtos e serviços',
      description: 'Cliente informa necessidade e envia pedido com vínculo ao veículo.',
      appArea: 'Solicitar orçamento',
      status: 'Disponível no MVP',
    },
    {
      id: 'RF08',
      title: 'Enviar solicitação de orçamento para o administrador',
      description: 'A solicitação gera protocolo e entra no fluxo de atendimento administrativo.',
      appArea: 'Painel administrativo',
      status: 'Fluxo administrativo',
    },
    {
      id: 'RF09',
      title: 'Mostrar histórico de serviços do veículo',
      description: 'Consulta unificada dos serviços já executados por veículo.',
      appArea: 'Histórico de serviços',
      status: 'Disponível na demo',
    },
    {
      id: 'RF10',
      title: 'Lembrete de revisão a cada 3 meses',
      description: 'Notificação recorrente incentiva manutenção preventiva e retorno à oficina.',
      appArea: 'Central de notificações',
      status: 'Disponível na demo',
    },
  ],

  featureHighlights: [
    {
      id: 'feature-1',
      title: 'Confiança do cliente',
      description: 'Acompanhamento transparente do serviço aumenta a segurança e reduz dúvidas durante o atendimento.',
    },
    {
      id: 'feature-2',
      title: 'Comunicação oficina-consumidor',
      description: 'Atualizações, notificações e retorno de orçamento melhoram o contato entre a equipe e o cliente.',
    },
    {
      id: 'feature-3',
      title: 'Retorno com promoções e revisões',
      description: 'Campanhas e lembretes recorrentes ajudam a gerar novas visitas e aumentar o faturamento.',
    },
    {
      id: 'feature-4',
      title: 'Histórico do veículo organizado',
      description: 'Todas as manutenções ficam registradas em um só lugar para consulta rápida e confiável.',
    },
    {
      id: 'feature-5',
      title: 'Orçamento e acompanhamento digitais',
      description: 'O app digitaliza a solicitação de orçamento e o acompanhamento do serviço do início ao fim.',
    },
  ],
  userFlows: [
    {
      id: 'flow-1',
      title: 'Fluxo 1 — acompanhamento do serviço',
      summary: 'Cliente acompanha a entrada do veículo, o avanço do atendimento e a notificação de retirada.',
      steps: [
        'Cliente leva o carro à oficina.',
        'Admin cadastra entrada do veículo.',
        'Status é atualizado no sistema.',
        'Cliente acompanha pelo app.',
        'Quando finalizar, recebe notificação de retirada.',
      ],
      outcome: 'Mais transparência durante toda a execução do serviço.',
    },
    {
      id: 'flow-2',
      title: 'Fluxo 2 — solicitação de orçamento',
      summary: 'Catálogo conectado ao time administrativo para cotações de pneus, peças e serviços.',
      steps: [
        'Cliente entra na área de pneus/peças.',
        'Seleciona item ou serviço.',
        'Clica em solicitar orçamento.',
        'Pedido vai para o admin.',
        'Admin analisa e responde.',
      ],
      outcome: 'A equipe responde com protocolo e retorno comercial centralizado.',
    },
    {
      id: 'flow-3',
      title: 'Fluxo 3 — revisão periódica',
      summary: 'Histórico salva a conclusão do serviço e ativa o lembrete automático de manutenção.',
      steps: [
        'Serviço concluído e salvo no histórico.',
        'Sistema registra data da última revisão.',
        'Após 3 meses, cliente recebe lembrete automático.',
      ],
      outcome: 'O app ajuda a aumentar recorrência e retenção da oficina.',
    },
  ],
  vehicles: [
    {
      id: 'veh-1',
      plate: 'BRA2E19',
      brand: 'Jeep',
      model: 'Compass Longitude',
      year: 2021,
      mileage: 48210,
      notes: 'Cliente prefere contato via WhatsApp após 18h.',
      statusLabel: 'Em atendimento',
    },
    {
      id: 'veh-2',
      plate: 'GOL9A45',
      brand: 'Volkswagen',
      model: 'Gol 1.6 MSI',
      year: 2019,
      mileage: 76340,
      notes: 'Uso diário para trabalho, priorizar revisão rápida.',
      statusLabel: 'Revisão trimestral pendente',
    },
  ],
  activeServices: [
    {
      id: 'srv-1',
      vehicleId: 'veh-1',
      title: 'Revisão completa + alinhamento',
      description: 'Troca de óleo, filtros, alinhamento, scanner e inspeção do sistema de freios.',
      eta: 'Hoje, 17:40',
      budget: 'R$ 1.280,00',
      technician: 'Técnico responsável: Marcos',
      steps: [
        { label: 'Veículo recebido', completed: true },
        { label: 'Em análise', completed: true },
        { label: 'Orçamento em preparação', completed: true },
        { label: 'Serviço aprovado', completed: true },
        { label: 'Em execução', completed: true, current: true },
        { label: 'Finalizado', completed: false },
        { label: 'Pronto para retirada', completed: false },
      ],
    },
  ],
  promotions: [
    {
      id: 'pro-1',
      title: 'Revisão completa com desconto',
      description: 'Troca de óleo premium + filtro + checklist com 20 itens em promoção nesta semana.',
      highlight: '15% OFF',
      cta: 'Agendar agora',
    },
    {
      id: 'pro-2',
      title: 'Pneus aro 18 com instalação grátis',
      description: 'Marcas premium com alinhamento e balanceamento inclusos.',
      highlight: '4x sem juros',
      cta: 'Solicitar orçamento',
    },
    {
      id: 'pro-3',
      title: 'Campanha freios + suspensão',
      description: 'Avaliação gratuita para pastilhas, discos, amortecedores e pivôs.',
      highlight: 'Check-up grátis',
      cta: 'Receber detalhes',
    },
  ],
  catalog: [
    {
      id: 'cat-1',
      name: 'Pneu Michelin Primacy 4',
      category: 'Pneus',
      description: 'Alta aderência e conforto para uso urbano e rodoviário.',
      price: 'R$ 899,00',
      stock: '8 unidades',
    },
    {
      id: 'cat-2',
      name: 'Bateria Moura 60Ah',
      category: 'Baterias',
      description: 'Excelente partida e durabilidade para veículos leves.',
      price: 'R$ 579,00',
      stock: '12 unidades',
    },
    {
      id: 'cat-3',
      name: 'Kit pastilha dianteira Bosch',
      category: 'Freios',
      description: 'Reposição com baixo ruído e maior vida útil.',
      price: 'R$ 249,00',
      stock: '15 kits',
    },
    {
      id: 'cat-4',
      name: 'Revisão preventiva 40 mil km',
      category: 'Serviços',
      description: 'Inspeção geral com scanner, fluidos e filtros essenciais.',
      price: 'Sob consulta',
      stock: 'Agenda disponível',
    },
  ],
  history: [
    {
      id: 'his-1',
      vehicleId: 'veh-1',
      title: 'Troca de óleo',
      date: '10/01/2026',
      details: 'Óleo sintético 5W30, filtro de óleo e revisão visual de vazamentos.',
      amount: 'R$ 390,00',
    },
    {
      id: 'his-2',
      vehicleId: 'veh-1',
      title: 'Alinhamento e balanceamento',
      date: '10/01/2026',
      details: 'Ajuste da geometria e balanceamento das quatro rodas.',
      amount: 'R$ 180,00',
    },
    {
      id: 'his-3',
      vehicleId: 'veh-1',
      title: 'Troca de pastilhas de freio',
      date: '22/03/2026',
      details: 'Substituição do jogo dianteiro com limpeza do conjunto.',
      amount: 'R$ 420,00',
    },
    {
      id: 'his-4',
      vehicleId: 'veh-1',
      title: 'Revisão preventiva',
      date: '15/06/2026',
      details: 'Checklist de segurança, bateria, freios, suspensão e fluidos.',
      amount: 'R$ 610,00',
    },
  ],
  notifications: [
    {
      id: 'not-1',
      type: 'service',
      title: 'Serviço em andamento',
      message: 'Seu Compass já está em execução na oficina e segue dentro do prazo estimado.',
      date: 'Hoje • 14:32',
      read: false,
    },
    {
      id: 'not-2',
      type: 'pickup',
      title: 'Veículo pronto para retirada',
      message: 'Seu veículo já está pronto para retirada na Impacto Prime: Taboão da Serra.',
      date: 'Hoje • 17:45',
      read: false,
      details: {
        finalAmount: 'R$ 1.280,00',
        businessHours: 'Segunda a sexta, das 8h às 18h • Sábado, das 8h às 12h',
        technicianNotes: 'Alinhamento concluído e pressão dos pneus revisada. Recomendado retorno em 5.000 km para inspeção preventiva.',
      },
    },
    {
      id: 'not-3',
      type: 'promo',
      title: 'Promoção da semana',
      message: 'Revisão completa com 15% de desconto nesta semana. Aproveite!',
      date: '19 mar 2026',
      read: true,
    },
    {
      id: 'not-4',
      type: 'revision',
      title: 'Lembrete de revisão periódica',
      message: 'Já faz 3 meses desde sua última revisão. Agende uma nova visita na Impacto Prime.',
      date: '18 mar 2026',
      read: true,
    },
  ],
  screenSuggestions: [
    {
      id: 'screen-1',
      title: '1. Splash Screen',
      subtitle: 'Primeiro contato com a marca Impacto Prime.',
      highlights: ['Logo da Impacto Prime', 'Tela curta de abertura', 'Transição para login'],
    },
    {
      id: 'screen-2',
      title: '2. Login / Cadastro',
      subtitle: 'Acesso rápido com credenciais simples.',
      highlights: ['Entrada por e-mail ou telefone', 'Campo de senha', 'Recuperação de acesso'],
    },
    {
      id: 'screen-3',
      title: '3. Home',
      subtitle: 'Resumo geral da experiência do cliente.',
      highlights: ['Promoções em destaque', 'Status atual do carro', 'Atalhos principais'],
    },
    {
      id: 'screen-4',
      title: '4. Meus Veículos',
      subtitle: 'Gestão completa da frota do cliente.',
      highlights: ['Lista de veículos cadastrados', 'Informações principais por veículo', 'Botão para adicionar veículo'],
    },
    {
      id: 'screen-5',
      title: '5. Acompanhar Serviço',
      subtitle: 'Transparência total durante o atendimento.',
      highlights: ['Status atual do serviço', 'Timeline do processo', 'Observações da oficina'],
    },
    {
      id: 'screen-6',
      title: '6. Loja / Catálogo',
      subtitle: 'Consulta de produtos e serviços disponíveis.',
      highlights: ['Pneus', 'Peças', 'Filtros por categoria'],
    },
    {
      id: 'screen-7',
      title: '7. Solicitar Orçamento',
      subtitle: 'Canal rápido para pedir cotações.',
      highlights: ['Formulário simples', 'Descrição do serviço', 'Envio ao admin'],
    },
    {
      id: 'screen-8',
      title: '8. Histórico',
      subtitle: 'Consulta de serviços já realizados.',
      highlights: ['Serviços realizados', 'Datas', 'Valores ou observações'],
    },
    {
      id: 'screen-9',
      title: '9. Notificações',
      subtitle: 'Mensagens importantes centralizadas no app.',
      highlights: ['Promoções', 'Carro pronto', 'Lembretes de revisão'],
    },
    {
      id: 'screen-10',
      title: '10. Perfil',
      subtitle: 'Dados cadastrais e preferências do cliente.',
      highlights: ['Dados do cliente', 'Veículos vinculados', 'Preferências de notificação'],
    },
  ],
  adminTasks: [
    {
      id: 'adm-1',
      title: 'Responder orçamento de pneus',
      description: 'Cliente Lucas Martins solicitou cotação para 4 pneus aro 18.',
      status: 'Pendente',
    },
    {
      id: 'adm-2',
      title: 'Atualizar status do Compass',
      description: 'Mover serviço para etapa Finalizado e liberar retirada.',
      status: 'Em andamento',
    },
    {
      id: 'adm-3',
      title: 'Cadastrar campanha sazonal',
      description: 'Subir promoção de alinhamento e balanceamento de abril.',
      status: 'Planejado',
    },
  ],
};
