import { DashboardData } from '../../types';

export const mockDashboardData: DashboardData = {
  customer: {
    name: 'Lucas Martins',
    unit: 'Impacto Prime • Taboão da Serra',
    nextRevision: '20 jun 2026',
    memberSince: 'Cliente desde jan 2024',
  },
  kpis: [
    { id: 'kpi-1', label: 'Veículos cadastrados', value: '2' },
    { id: 'kpi-2', label: 'Serviço em andamento', value: '1 ativo' },
    { id: 'kpi-3', label: 'Solicitações de orçamento', value: '3 este mês' },
  ],
  shortcuts: [
    {
      id: 'short-1',
      label: 'Acompanhar serviço',
      description: 'Timeline em tempo real do carro na oficina.',
    },
    {
      id: 'short-2',
      label: 'Solicitar orçamento',
      description: 'Envio rápido de pneus, peças e revisões.',
    },
    {
      id: 'short-3',
      label: 'Loja de pneus',
      description: 'Catálogo com itens em destaque da unidade.',
    },
    {
      id: 'short-4',
      label: 'Histórico do veículo',
      description: 'Tudo o que já foi feito no carro.',
    },
  ],
  featureHighlights: [
    {
      id: 'feature-1',
      title: 'RF04 • Status do serviço',
      description: 'Cliente acompanha cada etapa: recebimento, análise, aprovação, execução e retirada.',
    },
    {
      id: 'feature-2',
      title: 'RF07/RF08 • Orçamento digital',
      description: 'Solicitação vai para o admin e retorna para o cliente com protocolo.',
    },
    {
      id: 'feature-3',
      title: 'RF10 • Lembrete trimestral',
      description: 'Notificações automatizadas ajudam na retenção e recorrência de revisão.',
    },
  ],
  vehicles: [
    {
      id: 'veh-1',
      plate: 'BRA2E19',
      brand: 'Jeep',
      model: 'Compass Longitude',
      year: 2021,
      mileage: 48210,
      notes: 'Cliente prefere contato via WhatsApp após 18h.',
      statusLabel: 'Em atendimento',
    },
    {
      id: 'veh-2',
      plate: 'GOL9A45',
      brand: 'Volkswagen',
      model: 'Gol 1.6 MSI',
      year: 2019,
      mileage: 76340,
      notes: 'Uso diário para trabalho, priorizar revisão rápida.',
      statusLabel: 'Revisão trimestral pendente',
    },
  ],
  activeServices: [
    {
      id: 'srv-1',
      vehicleId: 'veh-1',
      title: 'Revisão completa + alinhamento',
      description: 'Troca de óleo, filtros, alinhamento, scanner e inspeção do sistema de freios.',
      eta: 'Hoje, 17:40',
      budget: 'R$ 1.280,00',
      technician: 'Técnico responsável: Marcos',
      steps: [
        { label: 'Veículo recebido', completed: true },
        { label: 'Em análise', completed: true },
        { label: 'Orçamento em preparação', completed: true },
        { label: 'Serviço aprovado', completed: true },
        { label: 'Em execução', completed: true, current: true },
        { label: 'Finalizado', completed: false },
        { label: 'Pronto para retirada', completed: false },
      ],
    },
  ],
  promotions: [
    {
      id: 'pro-1',
      title: 'Revisão completa com desconto',
      description: 'Troca de óleo premium + filtro + checklist com 20 itens em promoção nesta semana.',
      highlight: '15% OFF',
      cta: 'Agendar agora',
    },
    {
      id: 'pro-2',
      title: 'Pneus aro 18 com instalação grátis',
      description: 'Marcas premium com alinhamento e balanceamento inclusos.',
      highlight: '4x sem juros',
      cta: 'Solicitar orçamento',
    },
    {
      id: 'pro-3',
      title: 'Campanha freios + suspensão',
      description: 'Avaliação gratuita para pastilhas, discos, amortecedores e pivôs.',
      highlight: 'Check-up grátis',
      cta: 'Receber detalhes',
    },
  ],
  catalog: [
    {
      id: 'cat-1',
      name: 'Pneu Michelin Primacy 4',
      category: 'Pneus',
      imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
      description: 'Alta aderência e conforto para uso urbano e rodoviário.',
      price: 'R$ 899,00',
      stock: '8 unidades',
    },
    {
      id: 'cat-2',
      name: 'Bateria Moura 60Ah',
      category: 'Baterias',
      imageUrl: 'https://images.unsplash.com/photo-1605664041954-6d6f3b5f89a9?auto=format&fit=crop&w=1200&q=80',
      description: 'Excelente partida e durabilidade para veículos leves.',
      price: 'R$ 579,00',
      stock: '12 unidades',
    },
    {
      id: 'cat-3',
      name: 'Kit pastilha dianteira Bosch',
      category: 'Freios',
      imageUrl: 'https://images.unsplash.com/photo-1613214149922-f1809c99b414?auto=format&fit=crop&w=1200&q=80',
      description: 'Reposição com baixo ruído e maior vida útil.',
      price: 'R$ 249,00',
      stock: '15 kits',
    },
    {
      id: 'cat-4',
      name: 'Filtro de óleo Tecfil',
      category: 'Filtros',
      imageUrl: 'https://images.unsplash.com/photo-1632823471565-1ecf4e8df567?auto=format&fit=crop&w=1200&q=80',
      description: 'Filtragem eficiente para manter o motor protegido no uso diário.',
      price: 'R$ 42,90',
      stock: '24 unidades',
    },
    {
      id: 'cat-5',
      name: 'Óleo sintético 5W30',
      category: 'Óleos',
      imageUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80',
      description: 'Lubrificante premium para melhor desempenho e proteção térmica.',
      price: 'R$ 69,90',
      stock: 'Sob encomenda',
    },
    {
      id: 'cat-6',
      name: 'Terminal de direção premium',
      category: 'Peças em geral',
      imageUrl: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1200&q=80',
      description: 'Peça de reposição para manutenção da direção com aplicação sob análise.',
      price: 'Sob consulta',
      stock: 'Aplicação confirmada pela oficina',
    },
  ],
  history: [
    {
      id: 'his-1',
      vehicleId: 'veh-1',
      title: 'Troca de óleo',
      date: '10 jan 2026',
      details: 'Óleo sintético 5W30, filtro de óleo e revisão visual de vazamentos.',
      amount: 'R$ 390,00',
    },
    {
      id: 'his-2',
      vehicleId: 'veh-1',
      title: 'Alinhamento e balanceamento',
      date: '10 jan 2026',
      details: 'Ajuste da geometria e balanceamento das quatro rodas.',
      amount: 'R$ 180,00',
    },
    {
      id: 'his-3',
      vehicleId: 'veh-1',
      title: 'Troca de pastilhas de freio',
      date: '22 mar 2026',
      details: 'Substituição do jogo dianteiro com limpeza do conjunto.',
      amount: 'R$ 420,00',
    },
    {
      id: 'his-4',
      vehicleId: 'veh-2',
      title: 'Revisão preventiva',
      date: '15 jun 2026',
      details: 'Checklist de segurança, bateria, freios, suspensão e fluidos.',
      amount: 'R$ 610,00',
    },
  ],
  notifications: [
    {
      id: 'not-1',
      type: 'service',
      title: 'Serviço em andamento',
      message: 'Seu Compass já está em execução na oficina e segue dentro do prazo estimado.',
      date: 'Hoje • 14:32',
      read: false,
    },
    {
      id: 'not-2',
      type: 'pickup',
      title: 'Veículo pronto para retirada',
      message: 'Seu veículo já está pronto para retirada na Impacto Prime: Taboão da Serra.',
      date: 'Hoje • 17:45',
      read: false,
    },
    {
      id: 'not-3',
      type: 'promo',
      title: 'Promoção da semana',
      message: 'Revisão completa com 15% de desconto nesta semana. Aproveite!',
      date: '19 mar 2026',
      read: true,
    },
    {
      id: 'not-4',
      type: 'revision',
      title: 'Lembrete de revisão periódica',
      message: 'Já faz 3 meses desde sua última revisão. Agende uma nova visita na Impacto Prime.',
      date: '18 mar 2026',
      read: true,
    },
  ],
  adminTasks: [
    {
      id: 'adm-1',
      title: 'Responder orçamento de pneus',
      description: 'Cliente Lucas Martins solicitou cotação para 4 pneus aro 18.',
      status: 'Pendente',
    },
    {
      id: 'adm-2',
      title: 'Atualizar status do Compass',
      description: 'Mover serviço para etapa Finalizado e liberar retirada.',
      status: 'Em andamento',
    },
    {
      id: 'adm-3',
      title: 'Cadastrar campanha sazonal',
      description: 'Subir promoção de alinhamento e balanceamento de abril.',
      status: 'Planejado',
    },
  ],
};
