name: Create Release Builds

jobs:
  build_android:
    name: Build Android Production (No Submit)
    type: build
    params:
      platform: android
      profile: productionNoSubmit
  build_ios:
    name: Build iOS Production
    type: build
    params:
      platform: ios
      profile: production
